version: '3.9'
services:
    mcp-connector:
        build: .
        command: ${AUTHTOKEN}
        image: mcp-connector
        container_name: mcp-connector-instance
        ports:
            - '12757:12757'
